
    // DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
    // All changes done to this file will be lost upon re-running the 'silence createapi' command.
    // If you want to create new API methods, define them in a new file.
    // Silence is a DEAL research team project, more info about us in https://deal.us.es

    'use_strict';
    
    import { BASE_URL, requestOptions } from './common.js';
    
    const itemsAPI_auto ={

    /**
    * Gets all items
    */
    getAll:async function(){
        let response = await axios.get(`${BASE_URL}/items`,requestOptions);
        return response.data;
    },

    /**
    * Gets an entry from 'items' by its primary key
    */
    getById:async function(itemId){
        let response = await axios.get(`${BASE_URL}/items/${itemId}`,requestOptions);
        return response.data[0];
    },

    /**
    * Creates a new entry in 'items'
    */
    create:async function(formData, ){
        let response = await axios.post(`${BASE_URL}/items`,formData, requestOptions);
        return response.data;
    },

    /**
    * Updates an existing entry in 'items' by its primary key
    */
    update:async function(formData, itemId){
        let response = await axios.put(`${BASE_URL}/items/${itemId}`,formData, requestOptions);
        return response.data;
    },

    /**
    * Deletes an existing entry in 'items' by its primary key
    */
    delete:async function(itemId){
        let response = await axios.delete(`${BASE_URL}/items/${itemId}`,requestOptions);
        return response.data;
    },
};

export {itemsAPI_auto};