DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS List;

CREATE TABLE Users (
  userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(512) NOT NULL,
  name VARCHAR(256) NOT NULL,
  surnames VARCHAR(256) NOT NULL
);

CREATE TABLE Lists(
  listId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  userId INT DEFAULT NULL,
  FOREIGN KEY (userId) REFERENCES Users (userId) ON DELETE CASCADE
);

CREATE TABLE Items (
  itemId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT NULL,
  quantity INT DEFAULT '1',
  purchased BOOLEAN NOT NULL DEFAULT 0,
  listId INT DEFAULT NULL,
  FOREIGN KEY (listId) REFERENCES Lists (listId) ON DELETE CASCADE
);